# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  galleryPublishingKey:
    secure: 0PgkUpRd+qAfL0WFe5pFmOE/KasEJY19wogMfkRzk1NFqFqfDGLIU+CPbd1ZoR+1  
  access_token:
    secure: kGlQZapsnS3J41iYVKMP4kqeYcSeFRPI3rXNxl5GwgkcnPiGJxQmU+HO30xaegQq
# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*/

install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
# Execute the script analyzer
  - ps: $results = Invoke-ScriptAnalyzer -Path .\functions -Recurse | where severity -eq "Error"
# Format the results
  - ps: $header = "<testsuite tests=`"$($results.Count)`">" 
  - ps: $body = $results | ForEach-Object {"<testcase classname=`"analyzer`" name=`"$($_.RuleName)`"><failure type=`"$($_.ScriptName)`">$($_.Message)</failure></testcase>"}
  - ps: $footer = "</testsuite>"
  - ps: $header + $body +$footer | out-file .\TestsResults.xml
# Upload results
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
# Fail if thre are issues
  - ps: if($results.Count -gt 0){throw "ScriptAnalyzer found $($results.Count) issues"}
# Deploy to Powershell Gallery only where there is a tag which will have the version number
  - ps: $deploy = $results.Count -eq 0 -and $env:APPVEYOR_REPO_BRANCH -eq "jtarquino/autopublish" -and $env:APPVEYOR_REPO_TAG
   
deploy_script:
  if ($deploy)
  {
    $moduleName = "ReportingServicesTools"
    $currentVersion = (Import-PowerShellDataFile .\$moduleName.psd1).ModuleVersion
    ((Get-Content .\ReportingServicesTools.psd1).replace("ModuleVersion = '$($data.ModuleVersion)'", "ModuleVersion = '$($env:APPVEYOR_REPO_TAG_NAME)'")) | Set-Content .\$moduleName.psd1
    Publish-Module -Path .\ -NuGetApiKey $env:galleryPublishingKey
  }

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email ""
  - git config --global user.name "Jaime Tarquino"
  - git add ReportingServicesTools.psd1  
  - git commit -m "Automatic Version Update from CI"
  - git push ...