# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  galleryPublishingKey:
    secure: 0PgkUpRd+qAfL0WFe5pFmOE/KasEJY19wogMfkRzk1NFqFqfDGLIU+CPbd1ZoR+1  
  access_token:
    secure: kGlQZapsnS3J41iYVKMP4kqeYcSeFRPI3rXNxl5GwgkcnPiGJxQmU+HO30xaegQq
# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*/

install:
- ps: Install-PackageProvider -Name NuGet -Force
- ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
- ps: |
    # Execute the script analyzer
    $results = Invoke-ScriptAnalyzer -Path .\functions -Recurse | where severity -eq "Error"
    # Format the results
    $header = "<testsuite tests=`"$($results.Count)`">" 
    $body = $results | ForEach-Object {"<testcase classname=`"analyzer`" name=`"$($_.RuleName)`"><failure type=`"$($_.ScriptName)`">$($_.Message)</failure></testcase>"}
    $footer = "</testsuite>"
    $header + $body +$footer | out-file .\TestsResults.xml
    # Upload results
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
    # Fail if thre are issues
    if($results.Count -gt 0){throw "ScriptAnalyzer found $($results.Count) issues"}
   
deploy_script:
- ps: |
    # Deploy to Powershell Gallery only where there is a tag which will have the version number
    write-host $env:APPVEYOR_REPO_BRANCH
    write-host $env:APPVEYOR_REPO_TAG
    write-host ($env:APPVEYOR_REPO_TAG)
    write-host ($env:APPVEYOR_REPO_TAG -eq $True)
    write-host ($env:APPVEYOR_REPO_TAG -eq "true")
    $deploy = ($env:APPVEYOR_REPO_BRANCH -eq "jtarquino/autopublish") -and ($env:APPVEYOR_REPO_TAG -eq $true)
    if ($deploy)
    {
      Write-Host "Starting Deployment tag $env:APPVEYOR_REPO_TAG_NAME"      
      $moduleName = "ReportingServicesTools"
      $currentVersion = (Import-PowerShellDataFile .\$moduleName.psd1).ModuleVersion
      ((Get-Content .\ReportingServicesTools.psd1).replace("ModuleVersion = '$($data.ModuleVersion)'", "ModuleVersion = '$($env:APPVEYOR_REPO_TAG_NAME)'")) | Set-Content .\$moduleName.psd1
      Publish-Module -Path .\ -NuGetApiKey $env:galleryPublishingKey
    }
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- git config --global user.email "reportingservices@hotmail.com"
- git config --global user.name "Jaime Tarquino"
- git add ReportingServicesTools.psd1  
- ps: if($deploy -eq $false){git add testresults.xml}
- ps: if($deploy -eq $false){git commit -m "Automatic Version Update from CI"}
- ps: if($deploy){write-host Push to Git}


  